#!/usr/bin/env bash
#
# Make the AppImage's forced X11 GDK backend a DEFAULT instead of an OVERRIDE.
#
# linuxdeploy-plugin-gtk writes `export GDK_BACKEND=x11` into the generated
# `apprun-hooks/linuxdeploy-plugin-gtk.sh`, and `AppRun` sources that hook AFTER
# the caller's environment. Nothing the user sets can win: `GDK_BACKEND=wayland
# ./Toolport.AppImage` prints "Trying x11 backend" and then panics in tao with
# "Failed to initialize gtk backend!".
#
# On Ubuntu/Debian that is merely opinionated. On a Wayland session whose
# Xwayland cannot survive the app (reproduced on Arch/Hyprland in a VMware guest
# on the vmwgfx driver) it is fatal in a way that is very hard to diagnose:
#
#   1. first launch  - EGL_BAD_PARAMETER, no window, and Xwayland dies
#                      SESSION-WIDE, breaking xdg-open for every other app;
#   2. every launch after that - nothing at all. DISPLAY still points at a
#                      socket the compositor holds, so the process connects and
#                      blocks forever in unix_wait_for_peer. No output, no
#                      error, no window. It is alive and waiting, not failing.
#
# Rewriting that one line to `export GDK_BACKEND="${GDK_BACKEND:-x11}"` keeps
# x11 as the default, so a user who sets nothing gets byte-identical behaviour,
# while letting anyone on Wayland opt out of the trap. The change is additive.
#
# The hook is generated by linuxdeploy at bundle time, so this runs AFTER
# `tauri build --bundles appimage` and rewrites the finished AppImage. It fails
# loudly if the line it expects is gone, so a linuxdeploy change can never
# silently drop the patch and ship an AppImage that looks fine.
#
# Repacking reuses the ORIGINAL AppImage runtime (the bytes before the squashfs
# image) and the original squashfs compression settings, rather than downloading
# appimagetool and stamping a different runtime in. Nothing new is fetched; the
# only new build dependency is squashfs-tools, which is in the Ubuntu archive.
#
# Usage: scripts/patch-appimage-gdk-backend.sh <path/to/App.AppImage>
#
# The AppImage is rewritten IN PLACE, so its Tauri updater signature no longer
# matches. Re-run `tauri signer sign` on it afterwards (release.yml does).
set -euo pipefail

appimage=${1:-}
if [ -z "$appimage" ]; then
  echo "usage: $0 <path/to/App.AppImage>" >&2
  exit 2
fi
if [ ! -f "$appimage" ]; then
  echo "error: no such file: $appimage" >&2
  exit 1
fi
appimage=$(readlink -f "$appimage")

for tool in mksquashfs unsquashfs; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "error: $tool not found. Install squashfs-tools." >&2
    exit 1
  fi
done

hook_rel=apprun-hooks/linuxdeploy-plugin-gtk.sh
old_line='export GDK_BACKEND=x11'
new_line='export GDK_BACKEND="${GDK_BACKEND:-x11}"'

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

chmod +x "$appimage"

# The squashfs image starts where the runtime ends, so the offset IS the size of
# the runtime we want to keep verbatim. Both --appimage-offset and
# --appimage-extract are handled by the runtime before it mounts anything, so
# neither needs FUSE (GitHub's runners have no libfuse2).
offset=$("$appimage" --appimage-offset)
case "$offset" in
  '' | *[!0-9]*)
    echo "error: --appimage-offset returned '$offset', which is not a byte count." >&2
    exit 1
    ;;
esac
if [ "$offset" -le 0 ]; then
  echo "error: --appimage-offset returned $offset." >&2
  exit 1
fi

# Match the original image's compression so the patched AppImage stays the same
# shape and size class as the one linuxdeploy produced.
superblock=$(unsquashfs -o "$offset" -s "$appimage")
comp=$(printf '%s\n' "$superblock" | awk '/^Compression/ { print $2; exit }')
block=$(printf '%s\n' "$superblock" | awk '/^Block size/ { print $3; exit }')
if [ -z "$comp" ] || [ -z "$block" ]; then
  echo "error: could not read the squashfs superblock:" >&2
  printf '%s\n' "$superblock" >&2
  exit 1
fi
echo "runtime=${offset}B compression=${comp} block=${block}"

head -c "$offset" "$appimage" >"$work/runtime"
runtime_size=$(stat -c %s "$work/runtime")
if [ "$runtime_size" != "$offset" ]; then
  echo "error: kept $runtime_size runtime bytes, wanted $offset." >&2
  exit 1
fi

(cd "$work" && "$appimage" --appimage-extract >/dev/null)
appdir=$work/squashfs-root
if [ ! -d "$appdir" ]; then
  echo "error: --appimage-extract produced no squashfs-root." >&2
  exit 1
fi

hook=$appdir/$hook_rel
if [ ! -f "$hook" ]; then
  echo "error: $hook_rel is missing from the AppImage." >&2
  echo "linuxdeploy-plugin-gtk changed its layout. Re-check the backend forcing" >&2
  echo "before releasing; do not just delete this step." >&2
  exit 1
fi
if ! grep -qF "$old_line" "$hook"; then
  echo "error: '$old_line' not found in $hook_rel." >&2
  echo "linuxdeploy-plugin-gtk changed. If it no longer forces the backend, drop" >&2
  echo "this step. If it forces it a different way, patch that instead. Hook was:" >&2
  sed -n '1,40p' "$hook" >&2
  exit 1
fi

# x11 must be the WHOLE value. `\b` is not enough: a comma is a word boundary, so
# it would match `GDK_BACKEND=x11,wayland` and silently truncate the list. The
# optional trailing group preserves the comment linuxdeploy writes on that line.
sed -i 's|^export GDK_BACKEND=x11\([[:space:]].*\)\{0,1\}$|export GDK_BACKEND="${GDK_BACKEND:-x11}"\1|' "$hook"
if ! grep -qF "$new_line" "$hook"; then
  echo "error: the rewrite did not apply to $hook_rel." >&2
  exit 1
fi
if grep -qE '^export GDK_BACKEND=x11([[:space:]]|$)' "$hook"; then
  echo "error: an unconditional GDK_BACKEND assignment survived the rewrite." >&2
  exit 1
fi

mksquashfs "$appdir" "$work/image.squashfs" \
  -root-owned -noappend -no-progress -no-xattrs -mkfs-time 0 \
  -comp "$comp" -b "$block" >/dev/null

cat "$work/runtime" "$work/image.squashfs" >"$work/patched.AppImage"
chmod +x "$work/patched.AppImage"

# Prove the round trip BEFORE overwriting the release artifact: a repack that
# quietly dropped files would otherwise ship.
mkdir -p "$work/verify"
(cd "$work/verify" && "$work/patched.AppImage" --appimage-extract >/dev/null)
repacked=$work/verify/squashfs-root
if ! grep -qF "$new_line" "$repacked/$hook_rel"; then
  echo "error: the repacked AppImage does not contain the patched hook." >&2
  exit 1
fi
if [ ! -x "$repacked/AppRun" ]; then
  echo "error: AppRun is missing or not executable after the repack." >&2
  exit 1
fi
before=$(find "$appdir" | wc -l)
after=$(find "$repacked" | wc -l)
if [ "$before" != "$after" ]; then
  echo "error: the repack changed the file count ($before -> $after)." >&2
  exit 1
fi

mv "$work/patched.AppImage" "$appimage"
chmod +x "$appimage"
echo "patched $appimage ($after entries; GDK_BACKEND is now overridable)"
