#!/usr/bin/env bash
#
# Render packaging/linux/aur/{PKGBUILD,.SRCINFO} for a published release.
#
# Why a native Arch package exists at all: the fat AppImage bundles Ubuntu
# 22.04's libwebkit2gtk-4.1, which is old enough to have no WebKitGPUProcess and
# cannot initialise EGL against a current Mesa. On Arch that shows up as a window
# that opens grey and empty while WebKitWebProcess aborts on EGL_BAD_PARAMETER
# every launch. It is the bundle, not the machine: the same session renders fine
# through the system WebKitGTK. No WEBKIT_* environment variable avoids it, and
# displacing only the bundled WebKit just surfaces the next ABI mismatch
# (gst_debug_log_id, then g_once_init_leave_pointer). A bundled browser engine
# and a rolling-release GPU stack cannot be made to agree, so don't try: ship a
# package that links the host's WebKitGTK, which is what the .deb already does
# for Debian/Ubuntu. This repackages that same .deb payload with real Arch
# dependencies. The fat AppImage is unchanged and still correct on Ubuntu/Debian.
#
# Both files are generated from the variables below so they cannot drift from
# each other; .SRCINFO is emitted directly rather than via `makepkg
# --printsrcinfo` so this runs on any Linux, not just Arch.
#
# Usage: scripts/render-aur.sh <version> [outdir]
#   version  release version WITHOUT the leading v, e.g. 1.15.0
#   outdir   defaults to packaging/linux/aur
#
# Needs curl + sha256sum and network access: the checksums must come from the
# assets that were actually published, never from a previous release.
set -euo pipefail

version=${1:-}
outdir=${2:-packaging/linux/aur}

if [ -z "$version" ]; then
  echo "usage: $0 <version> [outdir]" >&2
  exit 2
fi
version=${version#v}
# Arch pkgver forbids '-', and a prerelease would sort ABOVE the stable release
# it precedes under any mangling of it. The AUR only ever carries stable.
if ! printf '%s' "$version" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+$'; then
  echo "error: '$version' is not a stable X.Y.Z version; the AUR package is stable-only." >&2
  exit 1
fi

pkgname=toolport-bin
pkgrel=1
repo=tsouth89/toolport
url="https://github.com/$repo"
pkgdesc='One MCP endpoint for every AI client: governance, approvals, and audit for your MCP servers'
deb_name="Toolport_${version}_amd64.deb"
deb_url="$url/releases/download/v${version}/${deb_name}"
license_url="https://raw.githubusercontent.com/$repo/v${version}/LICENSE"

# Direct link-time dependencies only; webkit2gtk-4.1 already pulls libsoup3,
# glib2 and the gstreamer stack. xdotool provides libxdo, which tauri links for
# the global-shortcut/window plumbing.
depends=(webkit2gtk-4.1 gtk3 libayatana-appindicator xdotool openssl dbus hicolor-icon-theme)
optdepends=(
  'gnome-keyring: store MCP server secrets in the system keyring'
  'libsecret: Secret Service backend for saved credentials'
)

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

fetch_sha() {
  local target=$1 dest=$2
  if ! curl -fsSL --retry 3 -o "$dest" "$target"; then
    echo "error: could not download $target" >&2
    echo "The release must be PUBLISHED first; draft assets 404." >&2
    exit 1
  fi
  sha256sum "$dest" | awk '{ print $1 }'
}

echo "fetching $deb_url" >&2
deb_sha=$(fetch_sha "$deb_url" "$tmp/pkg.deb")
echo "fetching $license_url" >&2
license_sha=$(fetch_sha "$license_url" "$tmp/LICENSE")

mkdir -p "$outdir"

# Build the quoted array literals here rather than inside the heredoc, where a
# nested command substitution would fight the heredoc's own backslash rules.
depends_line=$(printf "'%s' " "${depends[@]}")
depends_line=${depends_line% }
optdepends_line=$(printf "'%s' " "${optdepends[@]}")
optdepends_line=${optdepends_line% }

cat >"$outdir/PKGBUILD" <<PKGBUILD
# Maintainer: South Forge AI <https://github.com/tsouth89/toolport/issues>
#
# GENERATED by scripts/render-aur.sh in $url - edit the script, not this file.
#
# Repackages the official .deb rather than bundling a browser engine, so Toolport
# links the HOST WebKitGTK. That is the only thing that stays correct on a rolling
# release; the fat AppImage carries Ubuntu 22.04's WebKitGTK and cannot initialise
# EGL against current Mesa. See the Linux notes in the project README.
pkgname=$pkgname
pkgver=$version
pkgrel=$pkgrel
pkgdesc="$pkgdesc"
arch=('x86_64')
url="$url"
license=('MIT')
depends=($depends_line)
optdepends=($optdepends_line)
provides=('toolport')
conflicts=('toolport')
# Prebuilt upstream binaries: stripping them or hunting for debug symbols only
# damages the shipped artifact.
options=('!strip' '!debug' '!emptydirs')
source=("\$pkgname-\$pkgver.deb::$deb_url"
        "LICENSE-\$pkgver::$license_url")
sha256sums=('$deb_sha'
            '$license_sha')

package() {
  # A .deb is an ar archive holding data.tar.<comp>. bsdtar (libarchive, already
  # required by makepkg) reads both layers, so this keeps working whatever
  # compression the tauri deb bundler picks - gz today.
  bsdtar -xf "\$srcdir/\$pkgname-\$pkgver.deb" -C "\$srcdir"
  bsdtar -xf "\$srcdir"/data.tar.* -C "\$pkgdir"
  install -Dm644 "\$srcdir/LICENSE-\$pkgver" "\$pkgdir/usr/share/licenses/\$pkgname/LICENSE"
}
PKGBUILD

{
  printf 'pkgbase = %s
' "$pkgname"
  printf '	pkgdesc = %s
' "$pkgdesc"
  printf '	pkgver = %s
' "$version"
  printf '	pkgrel = %s
' "$pkgrel"
  printf '	url = %s
' "$url"
  printf '	arch = x86_64
'
  printf '	license = MIT
'
  for d in "${depends[@]}"; do printf '	depends = %s
' "$d"; done
  for o in "${optdepends[@]}"; do printf '	optdepends = %s
' "$o"; done
  printf '	provides = toolport
'
  printf '	conflicts = toolport
'
  printf '	options = !strip
	options = !debug
	options = !emptydirs
'
  printf '	source = %s-%s.deb::%s
' "$pkgname" "$version" "$deb_url"
  printf '	source = LICENSE-%s::%s
' "$version" "$license_url"
  printf '	sha256sums = %s
' "$deb_sha"
  printf '	sha256sums = %s
' "$license_sha"
  printf '
'
  printf 'pkgname = %s
' "$pkgname"
} >"$outdir/.SRCINFO"

echo "wrote $outdir/PKGBUILD and $outdir/.SRCINFO for $version" >&2
echo "  deb     $deb_sha" >&2
echo "  LICENSE $license_sha" >&2
